### ISSUE TITLE
encoding error in test_MorphemeGloss.py

### ISSUE THREAD

**Issue by paul-shannon** [paul-shannon/slexil#1]
@davidjamesbeck reports:

````
iMac-2:slexil David$ cd tests; make
python test_MorphemeGloss.py
  File "test_MorphemeGloss.py", line 5
SyntaxError: Non-ASCII character '\xe2' in file test_MorphemeGloss.py on line 5, but no encoding declared; see http://www.python.org/peps/pep-0263.html for details
make: *** [morphemeGloss] Error 1
iMac-2:tests David$ 
````
And suggests ````That looks like an easy one (same encoding problem as before)````
referring to his suggestion to add ````# -*- coding: utf-8 -*-```` to the top of MorphemeGloss.py

**Comment by paul-shannon** [comment]
@davidjamesbeck I added the ''''utf-8 coding'''' line.   Since this was not needed in my setup - I had not seen any error - could you let me know if it fixes the complaint that you encountered?

**Comment by davidjamesbeck** [comment]
2019/2/18: Issue appears to be fixed
