### ISSUE TITLE
demo8.py: an annotated example, how to download zipfiles 

### ISSUE THREAD

**Issue by paul-shannon** [paul-shannon/slexil#12]
@davidjamesbeck   [demo8.py](https://github.com/paul-shannon/slexil/blob/master/explorations/downloadZipFile/demo8.py) solves (I hope) all of the intricacies of zipfile downloads - in particular, of files whose names are not known till run time.

I added lots of comments to callbacks and routes so that this eminently forgettable stuff can be retrieved and used in webapp.py.  Which I hope to do later this week.

dash has many virtues, but it is also (I see this with feeling!) seriously brain-dead in several ways.

In particular, local storage of data in the browser is a hack.  They don't want us to store any state in the python server-side code, but my their solution is clumsy.  It leads, among other things, to the odd persistence problem you reported - in which you had to restart your browser to flush old state.

The other thing which I (and everyone else) finds especially lame is the restriction "one callback per output".   Meaning that you only one event (an input) can  change the state of a widget (the output).

Still and all, this is better and simpler than writing a hybrid python/javascript app.  And dash (now at version < 0.4) will mature over time.

I urge you, if you can find the time, to study demo8.py very closely - to understand and internalize all the protocols and idiosyncrasies used and documented there.

**Comment by davidjamesbeck** [comment]
Thanks, Paul, I’ll do that. The window I had to spend time messing things up has closed for now, but by the end of next week I might have some questions for you.

David

**Comment by davidjamesbeck** [comment]
Hi, Paul

A question about how git works: one thing that was confusing me was that it seems when I open a branch and edit a file, the changes to that file persist on my local drive even if I’ve checked out of the branch. Is that right? I don’t see different versions of the files on my drive (one for each branch)—or are they there and I don’t know where to look? 

David

**Comment by paul-shannon** [comment]
I usually create a branch on the github website.
Then checkout -b <branchname> on my laptop.   The set of files changes (or at least apparently change) on your laptop each time you checkout a different branch.

**Comment by paul-shannon** [comment]
Hi David,

Here’s the part of the github alexis webpage where you create a new branch:

**Comment by davidjamesbeck** [comment]
> I usually create a branch on the github website.

Ah, I think that is maybe the step I was missing. The tutorial I happened across didn’t make that part clear (or maybe was about a different type of workflow). Doing that makes things make sense to me …

As always, looks fiendishly opaque until you figure out how brain-dead simple it is.

David
