### ISSUE TITLE
order of operations

### ISSUE THREAD

**Issue by davidjamesbeck** [paul-shannon/slexil#14]
It occurs to me that we could reduce the number of steps by changing the order the user is asked to do things to:

1) title
2) select eaf
3) tier guide
4) terms
5) collapse sound and EAF + sound into one step
6) collapse create webpage and dsiplay webapage into a single step

**Comment by paul-shannon** [comment]
# 6 is complete.  @davidjamesbeck - could you tackle #5?   This will plunge you into the not-always-pleasant world of dash logic flow which is routed via callbacks and triggered by changes of state in DOM elements.  I will  be glad to confer along the way.

**Comment by davidjamesbeck** [comment]
Okay, first dumb question.

I’m not sure how to work with Dash in the sense that I am not sure how to see the effects of changes in the Python code on the operation of the web app. For example, on my new branch I have started to tinker with createZipFile, which now looks as follows:

def createZipFile(projectDir):

   currentDirectoryOnEntry = os.getcwd()
   #projectDir = os.path.join(PROJECTS_DIRECTORY, projectName)
   os.chdir(projectDir)
   print(projectDir)

   audioDir = "audio"
   filesToSave = [os.path.join("audio", f) for f in os.listdir(audioDir) if f.endswith('.wav')]
   #should name .html file according to title of project/text?
   
   filesToSave.insert(0, "text.html")
   #zipfile should also be named for project
   zipFilename = "webpage.zip"
   zipFilenameFullPath = os.path.join(currentDirectoryOnEntry, projectDir, zipFilename)
   zipHandle = ZipFile(zipFilename, 'w')

   #filesToSave needs to include ijal.css, ijalUtils.js
   parentDir = os.path.abspath(os.path.join(projectDir, os.pardir))
   print(parentDir)
##   CSSfile = os.path.join(parentDir,"ijal.css")
##   scriptFile = os.path.join(parentDir,"ijalUtils.js")
##   filesToSave.append(CSSfile)
##   filesToSave.append(scriptFile)

   for file in filesToSave:
      zipHandle.write(file)

   zipHandle.close()

   os.chdir(currentDirectoryOnEntry)
   return(zipFilenameFullPath)

In order to make this work, I need to have the right paths to the various files, which Dash tells me I do not, so I added the print() statements to see. However, I don’t get any output to the terminal I’m running (presumably because the terminal is executing the code generated by Dash and not the Python directly?). So, my question is generally about how you can work with Dash and check the values of the different variables it is using.

Cheers

David

**Comment by paul-shannon** [comment]
Hi David,

By far the best way to find your feet with Dash is to write your own separate tiny example, learn about Input, Output, State into callbacks, storing user-specific persistent data into hidden divs, chaining callbacks.   

Dash - for me - quickly becomes confusing, especially in a UI that has quite a few features, as our does.

Best by far is to divide and conquer, grasp the odd grammar and logic of Dash in a small example, expand by small steps, slowly get the point where you can see into the structure of webapp.py enough to make the changes you want.

Googling “plotly dash ‘hello world’” I found this, which looks promising:

  https://medium.freecodecamp.org/this-quick-intro-to-dash-will-get-you-to-hello-world-in-under-5-minutes-86f8ae22ca27

Forgive me if my comments or this suggestion is off-the-mark!

 - Paul

**Comment by davidjamesbeck** [comment]
Hi, Paul

Thanks for that link, it’s great and will be quite helpful as I learn Dash, but my question wasn’t exactly about how Dash works so much as how you work with Dash. The usual usual for checking Python code for me is to use IDLE or an IDE to monitor the states of things or use print() to query the states of things like variables as we go along, but that doesn’t work with Dash because the IDE/IDLE isn’t monitoring the app itself and doesn’t know what’s going on in the app, at least until you get an error message back. Maybe there’s no way around it, but I was wondering if there was a trick to it.

Cheers,

David

**Comment by paul-shannon** [comment]
Sorry to have misunderstood!

I use pdb - specifically pdb.set_trace() to pause the execution at a point in the code where I need to look more closely.  I see that I left some of these function calls in webapp.py, commented out but easy to find.

If you execute from the bash shell - not from within an IDE - this should give you the control you seek.

 - Paul

**Comment by davidjamesbeck** [comment]
Awesome, I’ll try it out.

David
