### ISSUE TITLE
webapp.py: simplify create web page section

### ISSUE THREAD

**Issue by paul-shannon** [paul-shannon/slexil#18]
The "Create Web Page" button, useful during development, needs to go.

**Comment by paul-shannon** [comment]
@davidjamesbeck 

Now simplified: just two buttons:
 
![image](https://user-images.githubusercontent.com/2480712/56474999-f997d680-6436-11e9-9e4d-e9fc2d9035fe.png)

If you are not already doing so, you may wish to keep current with the latest dash and plotly versions:

````
plotly                             3.8.1                 
dash                               0.41.0                
dash-core-components               0.46.0                
dash-dangerously-set-inner-html    0.0.2                 
dash-html-components               0.15.0                
dash-renderer                      0.22.0                
dash-table                         3.6.0
````
My way to do this is using pip:
````
~/anaconda/bin/pip install plotly --upgrade
~/anaconda/bin/pip install dash --upgrade
````

**Comment by davidjamesbeck** [comment]
Good stuff. That will make the process more transparent at the end.

David
