### ISSUE TITLE
deploy webapp at ualberta

### ISSUE THREAD

**Issue by paul-shannon** [paul-shannon/slexil#22]
@davidjamesbeck Maybe the computing group would just as soon get the code from us via github?

**Comment by davidjamesbeck** [comment]
Okay, after sending you my last message, I tried an experiment and ran webapp.py locally then copied the HTML code it generated into an index.html file

<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
      <meta charset="UTF-8">
        <title>IJAL Text Upload</title>
        <link rel="icon" type="image/x-icon" href="/_favicon.ico">
        <link rel="stylesheet" href="https://codepen.io/chriddyp/pen/bWLwgP.css">
<link rel="stylesheet" href="/assets/webapp.css?m=1559838148.23641">
    </head>
    <body>
        
<div id="react-entry-point">
    <div class="_dash-loading">
        Loading...
    </div>
</div>

        <footer>
            <script id="_dash-config" type="application/json">{"url_base_pathname": null, "requests_pathname_prefix": "/", "dev_tools_ui": false}</script>
            <script src="/_dash-component-suites/dash_renderer/react@16.8.6.min.js?v=0.22.0&m=1554834449"></script>
<script src="/_dash-component-suites/dash_renderer/react-dom@16.8.6.min.js?v=0.22.0&m=1554834449"></script>
<script src="/_dash-component-suites/dash_core_components/plotly-1.47.0.min.js?v=0.46.0&m=1554844515"></script>
<script src="/_dash-component-suites/dash_core_components/dash_core_components.min.js?v=0.46.0&m=1554907151"></script>
<script src="/_dash-component-suites/dash_table/bundle.js?v=3.6.0&m=1551749005"></script>
<script src="/_dash-component-suites/dash_html_components/dash_html_components.min.js?v=0.15.0&m=1553527950"></script>
<script src="/_dash-component-suites/dash_renderer/dash_renderer.min.js?v=0.22.0&m=1554907484"></script>
            <script id="_dash-renderer" type="application/javascript">var renderer = new DashRenderer();</script>
        </footer>
    </body>
</html>

This might be close to what we need, but when I try to open the page in the browser, it freezes on "Loading" and I get an error in the browser's console "ReferenceError: Can't find variable DashRenderer". Does that make sense to you, or am I just going about this the wrong way?

David

**Comment by paul-shannon** [comment]
Very cool that we have gotten to this point!

Here below what I see in my browser’s javascript console.  Make sense?   Seems to point to the need to have all those dash javascript libraries available. 
Maybe this will help?

   https://community.plot.ly/t/how-to-run-dash-on-a-public-ip/4796

 - Paul

**Comment by davidjamesbeck** [comment]
I didn't see your Java console output in the message, but I'll read through that site and the tutorial they reference to see if I can figure it out. I'll ask Michale if the calls to the dash libraries are right for the way the site is configured

David
