### ISSUE TITLE
naming of downloaded .zip

### ISSUE THREAD

**Issue by davidjamesbeck** [paul-shannon/slexil#25]
This is a pretty minor thing, but it might be nice to have the .zip file named for the project rather than the generic "webpage.zip" we're using. I know how to use createZipFile to assign the name from projectTitle_hiddenStorage, but this raises an error with the download—specifically, the app says it can't find "webpage.zip". I think the downloading of the file is done with 

@app.server.route('/PROJECTS/<path:urlpath>')
def downloadProjectZipFile(urlpath):
   print("--- serve_static_file")
   print("urlpath:  %s" % urlpath)
   fullPath = os.path.join("PROJECTS", urlpath)
   dirname = os.path.dirname(fullPath)
   filename = os.path.basename(fullPath)
   print("about to send %s, %s" % (dirname, filename))
   return flask.send_file(fullPath,
                          mimetype='application/zip',
                          as_attachment=True)

but I don't see where the file name "webpage.zip" comes in to play—is it in path:url somehow?

**Comment by paul-shannon** [comment]
Here’s a lazy fellow’s answer:

  slexil> grep -n webpage.zip *.py
    webapp.py:61:# which, by convention, are  ./PROJECTS/<someName>/webpage.zip:
    webapp.py:62:#    PROJECTS/daylight/webpage.zip
    webapp.py:63:#    PROJECTS/lokono/webpage.zip
    webapp.py:870:# webpage.zip, which is written into the href field of the html.A (or link) which nests the
    webapp.py:877:   return("%s/webpage.zip" % directory)
    webapp.py:943:   zipFilename = “webpage.zip”

Give me a shout (or a rude gesture!) if this doesn’t help straight away.

 - Paul

**Comment by davidjamesbeck** [comment]
Thanks, Paul, that helped. I think I’ve got this licked now.

David
