### ISSUE TITLE
on_eafUpload raises error when fed non-XML files

### ISSUE THREAD

**Issue by davidjamesbeck** [paul-shannon/slexil#26]
There is some terminal output for you below, but I think the gist of it is this: if in the step in the step in the process where you want to validate the .eaf file you select something that isn't even XML (say, the .wav file right below it in the list), the xmschema.is_valid parser chokes on it and, rather than simply returning "False" we get an error message from ElementTree. I have some vauge ideas about what we might do about it, but some of them depend on the capabilities of Dash (can it selectively disable any filename in the filedialog that doesn't end in .eaf?). Easiest fix would be to test the selected filename for the .eaf suffix. Or maybe there's a better way?

BTW, you don't have the latest code yet, I should be ready with another pull request this afternoon. I've changed the order of presentation and the page formatting, but I think we need to consider workflow control as a separate task.

============= projectDirectory_hiddenStorage changed, updateDownloadTextButtonHref: PROJECTS/Inferno
Inferno.zip
127.0.0.1 - - [03/May/2019 13:45:28] "POST /_dash-update-component HTTP/1.1" 200 -
=== displayText ''
127.0.0.1 - - [03/May/2019 13:45:28] "POST /_dash-update-component HTTP/1.1" 200 -
=== projectDirectory_hiddenStorage has been set, now change project pageTitle: 'PROJECTS/Inferno'
IJAL Upload: Inferno
127.0.0.1 - - [03/May/2019 13:45:28] "POST /_dash-update-component HTTP/1.1" 200 -
on_eafUpload, name: inferno-threeLines.wav
eaf file size: 1420124
[2019-05-03 13:45:37,938] ERROR in app: Exception on /_dash-update-component [POST]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/dash/dash.py", line 1151, in dispatch
    response.set_data(self.callback_map[output]['callback'](*args))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/dash/dash.py", line 1037, in add_context
    output_value = func(*args, **kwargs)
  File "webapp.py", line 526, in on_eafUpload
    validXML = schema.is_valid(filename)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/xmlschema/validators/xsdbase.py", line 516, in is_valid
    error = next(self.iter_errors(source, use_defaults=use_defaults), None)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/xmlschema/validators/xsdbase.py", line 534, in iter_errors
    for result in self.iter_decode(source, path=path, use_defaults=use_defaults, namespaces=namespaces):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/xmlschema/validators/schema.py", line 785, in iter_decode
    source = XMLResource(source=source, defuse=defuse, timeout=timeout, lazy=False)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/xmlschema/resources.py", line 240, in __init__
    self.source = source
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/xmlschema/resources.py", line 264, in __setattr__
    self._root, self._document, self._text, self._url = self._fromsource(value)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/xmlschema/resources.py", line 349, in _fromsource
    document = self.parse(resource)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/xml/etree/ElementTree.py", line 1197, in parse
    tree.parse(source, parser)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/xml/etree/ElementTree.py", line 598, in parse
    self._root = parser._parse_whole(source)
  File "<string>", line None
xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 1, column 5
127.0.0.1 - - [03/May/2019 13:45:37] "POST /_dash-update-component HTTP/1.1" 500 -

**Comment by paul-shannon** [comment]
Hi David,

Good point. webapp.py is currently susceptible to many errors like this.  

I proposed a solution last weekend - maybe it will help?   That is to create and test custom exceptions for all possible user errors.   All the custom exceptions should probably be a subclass of SlexilException - each specialized to handle a specific failure.   Bad xml, bad sound, tier mapping gone away, morpheme packing miststated, …

We want to develop this exception handling only in command-line python, not in webapp.py.

Make sense?

 - Paul

**Comment by davidjamesbeck** [comment]
I’m not sure I understand 100% how this will look, but I think it is a good idea. If we preclude some of the errors that occur when you do things in the wrong order by locking down the workflow and then do a good job of imagining all the possible screwups, I think this can be pretty robust.

David

**Comment by davidjamesbeck** [comment]
On this topic, I note the the dcc.Uploader element has an attribute "accept" which appears to limit the type of files that the user has access to. I stayed away from it because I would like a better sense of the vocabulary we can use to limit file types and I didn't find the documentation helpful. But this might streamline this side of the project by cutting down on the number of things users can do to mess things up,

**Comment by paul-shannon** [comment]
Hi David,

I wonder if it might be useful to adopt a different emphasis?  Which would be to ask:  what is the minimal functional form of this webapp?   What would be just barely good enough to be usable?  

My own view is that tabs were adequate, grammaticalTerms.txt could be explained, a few extra revealed operations could be tolerated.   I am a little bit afraid that trying to get the webapp really good will (or already has) gotten us into a precarious state.  And that good-enough is all we need -  to get this deployed and into the hands of users.  After which we respond to specific strong requests and bug reports.

Maybe?

 - Paul

**Comment by davidjamesbeck** [comment]
Hi, Paul

Once we get the animated playback and I fix it for the use case where there is no grammatical terms file, I think we’re already there. Is there something about the web app as it stands that worries you in particular right now? In my mind I was thinking that we would probably be in a position to deploy it next week and I could start inviting some people to try it out with some of the things that have been on hold while we’ve been working on this.

As for little things like the “accept” attribute and maybe using the textArea to cut and paste a list of grammatical terms in, those can be tinkered with down the road, if ever. Your suggestion to "create and test custom exceptions for all possible user errors” could be a longer term undertaking, though we might just wait for users to make them and tell us about them instead.

David

**Comment by paul-shannon** [comment]
Hi David,

> Your suggestion to "create and test custom exceptions for all possible user errors” could be a longer term undertaking, though we might just wait for users to make them and tell us about them instead

I ran the webapp after the latest merge a couple of days ago.  I used the Inferno demo.  Though I know the code, the UI, and the demo files pretty well, I made some choice which killed the app.   Since I had a console open to run the python, I saw the stack trace.   But in my role as a user, all I saw was a frozen web page.  

So it may be that the strategy “wait for users to [encounter program errors] and tell us about them” won’t get us very far.  All that I could have reported was that after I clicked the “Show Page” button, nothing happened, and  the webpage was unresponsive.  This happens and we likely alienate a user, learn nothing, see all of our good work go unused. 

I find the “create tier guide” component is confusing.  Can I offer some suggestions?

1) we already know a lot about the tiers from reading the eaf file.  We know the maximum tier count.  If there are only four tiers present, then alternate transcription and second translation need not be displayed.  

2) The middle column examples in the tier guide, in the context of the Inferno, left me confused.   Maybe a linguist would recognize them as examples right away.  I wondered if somehow I had selected the wrong eaf file.    Labeling the middle columns as “examples from Chatino” (or whatever the language it actually is) might help. Of maybe a question mark icon or help button with a popup that explains tiers and tier mapping.   That would reduce the cognitive and visual load of those lines from a (usually) unrelated language.

3) Can we deduce whether tabs or lines are used for word packing?   If so, then that selection disappears from the UI. If not, then this should be a required choice.   

4) Thinking of my claim in #1 above - that we know a lot about the structure of the eaf: we should display only and exactly the tier choices the user must make.  

I spent half a day over the weekend working on the animated playback task.  It turns out to be a hard problem, for which I have to better understand javascript Promises, how to iterate over them, how to interrupt and cancel them.  

You may recall that I forced us into this difficulty when I realized that, to create a standalone webpage, we had to break up the user’s audio file into pieces line by line.  Playback by start:stop times from a single audio file requires a webserver which supports range requests. CuPED does a good job on the automated-animated playback, but its dependence on range requests rules it out for us.   Emulating that behavior will take more study and experimentation from me.

I suspect we differ on a point of strategy now exposed.   Since you may not find my reasoning persuasive, may I cheat by making an appeal to authority?  I’ll give it a go!

When Donald Knuth said “premature optimization is the root of all evil” he was making an argument about code efficiency - that getting the code right was more important than getting it fast.  And that our intuitions about where inefficiencies lie are almost always wrong, so it is better to study a robust working program and refactor it for actual efficiencies later in the development process.

I rephrase Knuth using a carpentry metaphor: “premature finish work will ensure that your house falls down”.  We need to get the basic structure right.  Make sure the roof will keep out the rain, that the framing stands up to big winds and rough visitors.  

Which leads me to make these suggestions as we finish up slexil:

  1) We should anticipate, and catch, and explain every error the user can make.
     Do this first with the python classes, then adapt for the UI.
  2) Make do with line-by-line audio playback for now.
  3) Minimize the choices presented to the user in the tier guide
  4) test, test, test

What do you think?

 - Paul

**Comment by davidjamesbeck** [comment]
Hi, Paul


> On May 9, 2019, at 7:04 AM, Paul Shannon <notifications@github.com> wrote:
> 
> Hi David,
> 
> > Your suggestion to "create and test custom exceptions for all possible user errors” could be a longer term undertaking, though we might just wait for users to make them and tell us about them instead
> 
> I ran the webapp after the latest merge a couple of days ago. I used the Inferno demo. Though I know the code, the UI, and the demo files pretty well, I made some choice which killed the app. Since I had a console open to run the python, I saw the stack trace. But in my role as a user, all I saw was a frozen web page. 

I just tried it and ran into the same thing: I’m forced to pick a grammatical terms file, so the error is avoided. Could we somehow be running different versions? I am still not 100% confident that I’m using GIT right. 
> 
> So it may be that the strategy “wait for users to [encounter program errors] and tell us about them” won’t get us very far. All that I could have reported was that after I clicked the “Show Page” button, nothing happened, and the webpage was unresponsive. This happens and we likely alienate a user, learn nothing, see all of our good work go unused. 
> 
> I find the “create tier guide” component is confusing. Can I offer some suggestions?
> 
> 1) we already know a lot about the tiers from reading the eaf file. We know the maximum tier count. If there are only four tiers present, then alternate transcription and second translation need not be displayed. 

I like that idea.
> 
> 2) The middle column examples in the tier guide, in the context of the Inferno, left me confused. Maybe a linguist would recognize them as examples right away. I wondered if somehow I had selected the wrong eaf file. Labeling the middle columns as “examples from Chatino” (or whatever the language it actually is) might help. Of maybe a question mark icon or help button with a popup that explains tiers and tier mapping. That would reduce the cognitive and visual load of those lines from a (usually) unrelated language.

Good, I can try different things. I could show some screenshots to students to see if they “get it”, too.
> 
> 3) Can we deduce whether tabs or lines are used for word packing? If so, then that selection disappears from the UI. If not, then this should be a required choice. 

Also a good idea. I’m wondering if we need to provide for the line-packing (does that even work?) at this stage. I have only seen one example of a person using that (though they insisted it was “standard”).
> 
> 4) Thinking of my claim in #1 above - that we know a lot about the structure of the eaf: we should display only and exactly the tier choices the user must make. 

Yes, though a caveat would be that users may want different options, so the TierMap should provide the maximum number of options with the user free to select a subset.
> 
> I spent half a day over the weekend working on the animated playback task. It turns out to be a hard problem, for which I have to better understand javascript Promises, how to iterate over them, how to interrupt and cancel them. 
> 
> You may recall that I forced us into this difficulty when I realized that, to create a standalone webpage, we had to break up the user’s audio file into pieces line by line. Playback by start:stop times from a single audio file requires a webserver which supports range requests. CuPED does a good job on the automated-animated playback, but its dependence on range requests rules it out for us. Emulating that behavior will take more study and experimentation from me.

Sorry it is such a headache.
> 
> I suspect we differ on a point of strategy now exposed. Since you may not find my reasoning persuasive, may I cheat by making an appeal to authority? I’ll give it a go!
> 
> When Donald Knuth said “premature optimization is the root of all evil” he was making an argument about code efficiency - that getting the code right was more important than getting it fast. And that our intuitions about where inefficiencies lie are almost always wrong, so it is better to study a robust working program and refactor it for actual efficiencies later in the development process.
> 
> I rephrase Knuth using a carpentry metaphor: “premature finish work will ensure that your house falls down”. We need to get the basic structure right. Make sure the roof will keep out the rain, that the framing stands up to big winds and rough visitors. 
> 
> Which leads me to make these suggestions as we finish up slexil:
> 
> 1) We should anticipate, and catch, and explain every error the user can make.
> Do this first with the python classes, then adapt for the UI.
> 2) Make do with line-by-line audio playback for now.

Yes, though we can’t release this for general use without that feature—it is really what this is about for most users.

> 3) Minimize the choices presented to the user in the tier guide
> 4) test, test, test
> 
> What do you think?

It sounds fine to me, I am willing to work on whatever aspect of this you think needs attention at the moment. I know that lot of the stuff I’ve done is “finishing" work, but there are a few reasons for that. One is that doing this helps me understand the code. I am not fluent enough to read and comprehend easily, so doing little things helps me pull apart structure and see how it all fits together. I also don’t immediately grasp the flow of things, so rearranging the UI like I did (in what I hope was a non-destructive manner) was very helpful to me in terms of thinking through how a user is going to be interacting with the code and forestalling some of the errors that the app was susceptible to. That is probably the reverse of how a programmer thinks of things. And some of the cosmetics were just things I saw I could do quickly and easily in the cracks between other (non-coding) stuff. Oddly enough, I find simple programming tasks relaxing.

From your list above, I guess you’d like me to look into 1 and 3? I’ve started thinking about a subset of 1 (selecting incorrect file types at different stages) already. Your approach would be to write a test file that feeds incorrect choices to specific methods of the webapp, break it, and then fix it?

David

**Comment by paul-shannon** [comment]
Hi David,

How about this: I’ll just work on the animated playback, working to emulate CuPED’s nice effect, and leave all the rest up to you?   I think the time for handoff has come  - and that I risk being nothing more than a nag if I continue with my recent preachings.  It’s been a good run.  I don’t want to taint it by overstaying my role!

I will spend some time each week on the playback code till it passes muster, till you are happy with its performance.

Cheers!

 - Paul

**Comment by davidjamesbeck** [comment]
Hi, Paul

Okay, I’ll do my best—I feel like I’m missing something in our communication, I hope I haven’t put my foot in my mouth and upset you somehow. If I seem not to be following your advice, it isn’t intentional, it’s more not being sure in practical terms how to follow through on it. I’ve learned a lot in this process and appreciate how patiently you’ve walked me through everything. Any remaining deficiencies, as we say in the standard academic footnote, are my own responsibility.

David
