### ISSUE TITLE
could grammatical terms be pasted into textarea?

### ISSUE THREAD

**Issue by davidjamesbeck** [paul-shannon/slexil#27]
How trivial would it be to allow the user to paste a list of terms into the test area instead of uploading a file? It looks doable, but I might be kidding myself

**Comment by paul-shannon** [comment]
Famous Stanford computer scientist, Donald Knuth, inveighed us:

  premature optimization is the root of all evil

Your suggestion is good but I’d put it as a very low priority.   Let’s get this thing robust, working, deployed, in use.

**Comment by davidjamesbeck** [comment]
Oh yeah, I know to my own sorrow. I’m just thinking ahead a bit and trying to remember what it feels like to a be not-yet-jaded user with unreasonable expectations about what we should have been allowed to do.

Top priority now for me would be workflow control and the SlexilExceptions.

David

**Comment by paul-shannon** [comment]
How about I make a start on the exceptions this weekend, just before I turn to the auto-play feature?

**Comment by davidjamesbeck** [comment]
Sure, that sounds good. I’m about done with the current branch and I think I need to learn a bit more about Dash before looking into workflow control. I think the easiest way to prevent a large subset of catastrophic errors will be preventing the user opening <details> elements in the wrong order. It seems like checking the states of the various hidden storages would be one way to do that, but I’m not sure how to disable the opening of the elements. Adding conditions to the callbacks for various buttons would be another, but that seems somehow less elegant …

David
