### ISSUE TITLE
workflow control

### ISSUE THREAD

**Issue by davidjamesbeck** [paul-shannon/slexil#29]
Hi, Paul

So I've figured out how to write a callback that can check the hidden storage for a given disclosure element and see how the callbacks to each disclosure element could be made to change the value of the hidden storage element in the next disclosure element in the workflow sequence. What I haven't been able to figure out is how to disable the expansion of an element that the user isn't ready to access. There seems to be no "disabled" property for these things and doing something like closing the off-limits elements when the user tries to open them seems awkward (and setting the "open" attribute via the callback doesn't seem to have any effect, anyhow, so maybe the callback passes the signal on to whatever toggles the element?).

The solution that I can think of would be to defer constructing the contents of the disclosure elements until they are ready to be used, something like what already happens with the tier mapping. I wanted to check with you though, before undertaking something like that. I seems to me it might be a major restructuring of the app.

David

**Comment by paul-shannon** [comment]
maybe this will help?  I’ve used it often with buttons:


https://stackoverflow.com/questions/3710114/jquery-enabling-and-disabling-dom-elements-without-removing

**Comment by paul-shannon** [comment]
sorry - I forgot Dash does not give easy means to run javascript in the client.

How about this?

  https://community.plot.ly/t/how-to-disable-html-button/9859
  https://community.plot.ly/t/disable-a-component/9437
  https://github.com/plotly/dash-html-components/issues/32

Maybe that which works for button also works for the disclosure element?

**Comment by davidjamesbeck** [comment]
Unfortunately, the <disabled> property doesn’t apply to <details>. I’ve managed to plug an eternal javascript into a baby Dash app, but I can’t seem to make it add an event listener to a details component, let alone change that component’s properties. As you say, there isn’t a easy way to run the javascript in the Dash app, other than when the window loads.

David

**Comment by davidjamesbeck** [comment]
I think maybe I’ll just work on enabling buttons in the correct sequence instead of messing around with the disclosures. Even if we figure it out, it’s a lot of head-banging-against-the-wall time for relatively little return.

David
