### ISSUE TITLE
 Create Web Page > Download page: didn’t seem to do anything

### ISSUE THREAD

**Issue by paul-shannon** [paul-shannon/slexil#3]
@davidjamesbeck  This is one of the weakest parts of webapp.py.

I had hoped to find, in the plotly/dash components, a "choose file" widget - something like the ````dash_core_components.Upload```` widget.   When I did not find one, I skirted the UI challenge, and - with no notification to the user - write a zip file  ````PROJECTS/<title>/webpage.zip```` containing the html, javascript, and a nested subdirectory with the per-phrase audio files.

All of that seems to work.  But of course the UX is awful.

**Comment by davidjamesbeck** [comment]
Ah, I see it now, and the .zip file opens and works fine. I guess the nut to crack now is how to get the .zip file to the user. Could you place a URL as a link in the field with instructions "Click to download"?

**Comment by paul-shannon** [comment]
@davidjamesbeck I added a save button, and all the plumbing.
Some llimitations I know of, and one feature not yet implemented:
 - plotly dash offers (and we use) an Upload widget, but sadly does not yet offer anything comparable for file downloads.  This means I cannot offer the user the option of navigating to the download directory of their choice. For now I am saving the zip file to the server-side working directory, eg, PROJECTS/inferno  - which works when (for you and me) we run webapp.py on our own computers
  - To improve upon this - which must be done - and to offer download of the demo files, I have to do some more experiments.  Your idea - "place a URL as a link" makes sense, but I have not gotten that to work yet.
  - ````ijal.css```` is not yet part of the zip file.  That one should be easy
  - also: no progress yet on better rendering of the morpheme gloss line.

**Comment by paul-shannon** [comment]
@davidjamesbeck 
I isolated the download zip puzzle, found some examples, whittled them down to the code shown below, committed as ````explorations/downloadZipFile/demo5.py````.  Hoping you can look at this, that it can enter our repertoire of webapp techniques:
````
# derived from https://community.plot.ly/t/allowing-users-to-download-csv-on-click/5550/13
import flask
import dash
import dash_html_components as html

app = dash.Dash(__name__)

app.layout = html.Div([
    html.A(html.Button('Download the Inferno Demo', style={"margin-left": 30}), href='infernoDemo.zip'),
    html.Br(),
    html.A(html.Button('Download newly assembled text', style={"margin-left": 30}), href='webpage.zip'),
    ])

@app.server.route('/<filename>')
def download_zip(filename):
    return flask.send_file(filename,
                           mimetype='application/zip',
                           as_attachment=True)

if __name__ == '__main__':
    app.run_server()
````

**Comment by davidjamesbeck** [comment]
Hi, Paul

I pulled slexil and tried to run demo5.py. I got this output

iMac-2:slexil David$ python3 demo5.py
 * Serving Flask app "demo5" (lazy loading)
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://127.0.0.1:8050/ (Press CTRL+C to quit)
127.0.0.1 - - [26/Feb/2019 10:38:02] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [26/Feb/2019 10:38:02] "GET /_dash-layout HTTP/1.1" 200 -
127.0.0.1 - - [26/Feb/2019 10:38:02] "GET /_dash-dependencies HTTP/1.1" 200 -
127.0.0.1 - - [26/Feb/2019 10:38:03] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [26/Feb/2019 10:38:03] "GET /_dash-dependencies HTTP/1.1" 200 -
127.0.0.1 - - [26/Feb/2019 10:38:03] "GET /_dash-layout HTTP/1.1" 200 -
[2019-02-26 10:38:05,016] ERROR in app: Exception on /infernoDemo.zip [GET]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "demo5.py", line 17, in download_zip
    as_attachment=True)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/helpers.py", line 588, in send_file
    file = open(filename, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: '/Users/David/OpenSource/github/slexil/infernoDemo.zip'
127.0.0.1 - - [26/Feb/2019 10:38:05] "GET /infernoDemo.zip HTTP/1.1" 500 -

It looked to me like demo5 wanted a .zip file in the slexil folder, so I copied the webpage.zip file from PROJECTS/Inferno and renamed it infernoDemo.zip. When I tried it again, it worked fine—the .zip file downloaded and unpacked itself in my Downloads folder. So other than getting the path to the .zip file and the filename right, this works like a charm.

David

**Comment by paul-shannon** [comment]
Hi David,

The error message you get

  No such file or directory: '/Users/David/OpenSource/github/slexil/infernoDemo.zip'

suggests that you are not in the right directory when your run demo5.py.


Please try this:

    cd ~/OpenSource/github/explorations/downloadZipFile
    pwd
    ls -l

    python demo5.py

Please send me the full text from the whole session if the error persists.

 - Paul

**Comment by davidjamesbeck** [comment]
It worked fine this way, both buttons. Yay!

David

**Comment by paul-shannon** [comment]
@davidjamesbeck - New version, demo6.py, same directory.  Please give it a try.
This version will reward study (when you have a chance).  It is a distilled example of registering callbacks on a button, executing non-gui code, and then changing the state of another button when it is done.  It has taken me a while, but now the dash library's reactive logic makes a little bit of sense.

The weirdest part  (I'll put it in a demo tomorrow) is local, browser-based variable storage, using State objects in the callback.   Once these all (download via a flask static route, disabled buttons, callbacks with state) are working, I will weave them into webapp.py.

We probably want to disable all actions in webapp.py except for those which actually make sense to perform next.  That could immerse us in a nasty tangle of logic.  We'll see, and choose accordingly.

Let me know if you have any questions about demo6.py

![image](https://user-images.githubusercontent.com/2480712/53503000-17af0f00-3a64-11e9-92c8-66245d72c3b8.png)

**Comment by davidjamesbeck** [comment]
All’s working fine. I see how the code works—it is certainly one of those things that is very straighforward and transparent once you figure out how it do it, but before then is completely frustrating and opaque. I am beginning to see the Flask may be like that in general.

I agree that we need to make sure people don’t get ahead of themselves in the workflow. One thing along these lines I was going to mention is that the user shouldn’t be able to advance if the Title field is left blank in the first step—so the “submit” button needs to be disabled until a valid title is entered. If the field emits a signal of some kind when the user exits, then we can use the same callback logic you used in demo6.

David

**Comment by paul-shannon** [comment]
@davidjamesbeck   Still working on, and still confused about, the flask route and dash button callbck functions, in demo7.py.   I'll get it sooner or later, then move those techniques into webapp.py.  I'll keep you posted.

**Comment by davidjamesbeck** [comment]
Sounds good. It’s odd that this is so hard, you’d think this was sort of the prototypical thing you want a webapp to do. 

I may have some time to play with this today. I was thinking of adding a branch to the project and then seeing if I can add a secondary translation. That should help me familarize myself properly with the functionality, and if I’m successful and don’t make too much of a hash of it we can merge the branch eventually. I know the next big block of texts I’m expecting will have both Spanish and English translations.

Cheers,

David

**Comment by paul-shannon** [comment]
Sounds good, David.    You would make me happy if you use test-driven development, early and always.   

That is, no changes to code without an accompanying test; no commits before ensuring that all tests pass, both new tests and old.

**Comment by davidjamesbeck** [comment]
Yes, I’ll do my best with it. That is actually kind of my default way of doing things, since I’ve learned what little I know by trail and error, and errors are more informative if they come one at a time.

And I won’t commit anything until you’ve had a look at it. Your code is too pretty to spoil with my scribbling.

David

**Comment by paul-shannon** [comment]
@davidjamesbeck   I just committed updates to webapp.py, drawing upon things figured out in explorations/downloadZipFile/demo8.py
There is a new button for downloading the inferno demo.  A zipfile version of the newly assembled text is downloaded on request.

I suggest that we refine this version, making it less clunky, until it is good enough in your judgement to deploy on the Calgary website.

**Comment by davidjamesbeck** [comment]
Sounds good. I’ll have a look and make a list of things.

David

**Comment by paul-shannon** [comment]
Perhaps create a github issue for each?  That will make for easier tracking.

 - Paul

**Comment by davidjamesbeck** [comment]
Will do
