### ISSUE TITLE
window scrolling with Javascript

### ISSUE THREAD

**Issue by davidjamesbeck** [paul-shannon/slexil#35]
This kind of stuff is a perennial nightmare for me, jquery is not my friend. If you run the Monkey.html text, you'll see that once it gets to the bottom of the window and we start needing to scroll down (see the code below), the window doesn't scroll far enough. This is because the playback controls have a fixed position at the bottom of the screen and its height doesn't seem to be taken into account by .scrollIntoView(). I've tried to account for that in various ways (you can see both, the one that uses animate() is commented out) but it doesn't seem to work. Maybe you have some thoughts about how to fix this, or a better way to do it?

David

function setCurrentAnnotation(currentLine) {
        if (annotationPlaying != currentLine) {
            annotationPlaying.className ='line-wrapper';
        }
        currentLine.className += ' current-line';      
        annotationPlaying = currentLine;
        annotationPlaying.scrollIntoView(false);
        if (! isScrolledIntoView(annotationPlaying)) {
        	elementHeight = $(annotationPlaying).height()+46;
        	newScroll = $(window).scrollTop()+elementHeight;
        	$(window).scrollTop = newScroll;
//         	$(window).stop().animate({
//         		scrollTop: newScroll
//         		});
//        	console.log($(window).scrollTop());
        }
        //window.scroll(0,23px);
}
function isScrolledIntoView(elem)
{
    var docViewTop = $(window).scrollTop();
    var docViewBottom = docViewTop + $(window).height();

    var elemTop = $(elem).offset().top;
    var elemBottom = elemTop + $(elem).height()+23;

    return ((elemBottom <= docViewBottom) && (elemTop >= docViewTop));
}

**Comment by paul-shannon** [comment]
Hi David,

I did a fresh pull but cannot find “Monkey.html”.  Maybe it’s name is slightly different?

 - Paul

**Comment by davidjamesbeck** [comment]
Hi, Paul

Take a look now. I just did another push, maybe the repo wasn’t up to date? It should be in the Projects directory. 

David

**Comment by paul-shannon** [comment]
Hi David,

I don’t have any experience with the scroll-into-view operations and complexities, so I probably won’t be much help here.

Some ideas occur to me.  Quite likely you have already explored them.

1) This stackOverflow post looks promising, mentions a jQuery-free HTML element function:

    https://stackoverflow.com/questions/4884839/how-do-i-get-an-element-to-scroll-into-view-using-jquery
    https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollIntoView

2) Whenever confusion starts to pile up; whenever the ennui, frustration and dread arrives - it’s then, and despite my resistance, that I surrender and spend the time to recreate my problem in the smallest possible example.  You might be able to identify the problem and find a solution in 20 lines of html and javascript.

This doesn’t always work, but most of the time it serves me well.

Sorry I am unable to see into the problem enough to make a specific recommendation!

 - Paul

**Comment by davidjamesbeck** [comment]
Thanks, Paul. In a way, even this is reassuring because at least it means the problem isn’t something so trivial you could just look at the snippet and see how offbase it is. 

That post looks helpful, it spells things out in a way that makes experimentation easier. I have been reading StackOverflow posts about jquery all week but hadn’t seen that one. I wish I had better “Google foo”, as one of my colleagues puts it. 

I will keep at it. I have other sites where there are similar issues, but since those are mine, I cheat and used fixed window heights, etc., but here customizable is going to be high value for users. If I figure this out, it will have positive effects for other projects as well.

Cheers, 

David

**Comment by davidjamesbeck** [comment]
Working, hopefully soon working like a charm! $('html,body’) is my new best friend.

David

**Comment by paul-shannon** [comment]
Glad to hear this!

**Comment by davidjamesbeck** [comment]
Got it, seems to be working fine now. There's something icky about the slider function in the audio tag that means users can't navigate the page by seeking through the recording, but I don't think that is worth investing time in at this point.
