### ISSUE TITLE
corrections to daylight.yaml

### ISSUE THREAD

**Issue by paul-shannon** [paul-shannon/slexil#40]
@davidjamesbeck  - Many thanks for these corrections.   In the future I'll work at catching more such errors as I work.

I made a PR from your startStopTables branch, did the merge, and all seems to be well: all tests pass, daylight renders well.  Nice work!

--- from David  (email: 5 jul 2019)
Small things:  Line 1 has the hyphens in the first line, which you might not want, and line 12 has two • on the parsing line but one on the gloss line. Something’s up with line 16 as well. Line 32 gloss line starts “RR” but should be “IRR”. Line 34 hədʔiʷ’ should be hədʔiw’. If you don’t have a complete list of abbreviations to feed the app, I can find a text file of them somewhere.

Also, I notice that the player at the bottom in very tight to the last line of the text. There's probably a quick fix for that in the CSS (and something slexil would benefit from as well). The phonetic symbols are also a mix of serif and sans serif characters. Probably another CSS fix we could benefit from.

If you get a chance in the next couple of days, could you review the files on the startStop branch of the GitHub repo and, if you’re happy, merge that branch to main? I think I’d like to embark on the next leg of the adventure and see if this works once it’s on the university server. If so, I’d say we are pretty much in business!

**Comment by davidjamesbeck** [comment]
Hi, Paul 

No one ever catches all those errors by themselves. Not humanly possible—it’s not like programming where the processor alerts you to mistakes by blowing up in your face. I’m impressed by how clean those lines were.

David
