### ISSUE TITLE
merging startStopTables now complete?

### ISSUE THREAD

**Issue by paul-shannon** [paul-shannon/slexil#41]
@davidjamesbeck I got a little confused in the merge of your branch, apparently doing it twice, with slightly different results.  

I just pushed a change to two files.  In the first I still had a remnant startStopTable passed as a parameter to the Text constructore:
  - eafToWebPage.py (my exploratory code in the yaml->eaf->html project)
  - test_IJalLine.py: I commented out the audioData parameter:
 ````   x3 = IjalLine(doc, 3, tierGuide) # ,audioData='a,b,c')````

 I hope I got this right.  Do let me know.

**Comment by davidjamesbeck** [comment]
What you did looks right—as you can see, the audioData parameter in that line of code was a bit of nonsense I stuck in as a placeholder before I fixed the code not to need the startStopTable. Not sure why I didn’t get an error running make, I fixed that in a number of other places.

Cheers

David
