### ISSUE TITLE
upgrading dash

### ISSUE THREAD

**Issue by davidjamesbeck** [paul-shannon/slexil#42]
Hi, Paul

When I saw your message about Dash upgrades, I immediate and foolishly upgraded my local installation, so now I'll have to go through and deal with some of the changes. I'll do that, but I wanted to open this issue so we can track them.

Issue 1:

vpn0483:slexil David$ python3 webapp.py
Traceback (most recent call last):
  File "webapp.py", line 39, in <module>
    app = dash.Dash(__name__, external_stylesheets=external_stylesheets, static_folder='PROJECTS')
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/dash/dash.py", line 232, in __init__
    key + ' is no longer a valid keyword argument in Dash '
dash.exceptions.ObsoleteKwargException: static_folder is no longer a valid keyword argument in Dash since v1.0. See https://dash.plot.ly for details.

**Comment by davidjamesbeck** [comment]
Issue 1 is solved, at least as far as the error message goes, by commenting out  static_folder='PROJECTS' (the setting didn't seem to do anything anyway). However, we now have 

ISSUE 2
The text is no longer displayed when Show Button is clicked, instead the .html page is downloaded. Something about changing the src attribute of the iFrame calls "downloadProjectZipFile" (line 68), which sends the .html file to the user's computer. I can stop this by using the srcDoc attribute and feeding it the output of text.toHTML(). This also populates the iFrame, but we lose the CSS and Javascript. The Java console shows errors like:

[Error] SyntaxError: Unexpected token '<'
	(anonymous function) (jquery-3.3.1.min.js:1)
[Error] Did not parse stylesheet at 'http://0.0.0.0:60041/ijal.css' because non CSS MIME types are not allowed in strict mode.
[Error] SyntaxError: Unexpected token '<'
	(anonymous function) (ijalUtils.js:1)

**Comment by davidjamesbeck** [comment]
ISSUE 2 using the src attribute of the dash iFrame:

1) this attribute seems to feed a nested infinity of copies of the page itself into the iFrame. I have recreated this behaviour in a mini-test in Dash_Tests/textIFrame.py. Either there's a trick to specifying the path to the source (I've tried several different ways) or there's something buggy about the Dash iFrame.

2) any callback that has Output('storyIFrame', 'src') seems to trigger the callback at line 67:

@app.server.route('/PROJECTS/<path:urlpath>')
def downloadProjectZipFile(urlpath):
#    if urlpath[-1] != 'p':
#       return()
#    if urlpath[-1] == 'p':
   print("--- serve_static_file")
   print("urlpath:  %s" % urlpath)
   fullPath = os.path.join("PROJECTS", urlpath)
   dirname = os.path.dirname(fullPath)
   filename = os.path.basename(fullPath)
   print("about to send %s, %s" % (dirname, filename))
   return flask.send_file(fullPath,
						  mimetype='application/zip',
						  as_attachment=True)

I'm out of ideas for the day.

**Comment by davidjamesbeck** [comment]
ISSUE 3 (fixed):

updating yaml triggered a warning about using yaml.load(), apparently it is a security thing. I fixed text.py and some of the test file to use yaml.safe_load() instead and everything seems fine, all our tests now pass without warning

**Comment by paul-shannon** [comment]
HI @davidjamesbeck 

In your ````testIFrame.py```` - in order to be a good base for debugging the iframe problem - and I applaud your strategy of isolating it to some minimal code - you will probably need to add a route for the flask server to use.   This is mentioned [here](https://community.plot.ly/t/html-iframe-in-dash-layout/5281).   I hope the frustrations are not mounting up painfully high!

**Comment by davidjamesbeck** [comment]
Thanks for the tip. I wonder if this means we can collapse the two remaining frustrations into one, since the Flask callback is the root of the download-instead-of-update-iFrame problem. I was going to set up a minimal example to reproduce that as well.

Hopefully Michael will have some insight into the deployment problem. It might be something as simple as not having gunicorn installed (we should be so lucky.

**Comment by davidjamesbeck** [comment]
I added a new test file with a button to change the iFrame contents and the @server.route('/static/<path:path>’). Still no luck, but if we can get this test working I imagine it will solve both our problems with the iFrame

David

**Comment by paul-shannon** [comment]
@davidjamesbeck   I put Inferno.html  into subdirectory ````static/```` and now testIFrame2.py appears to (mostly) work.  Let me know what you think.

**Comment by davidjamesbeck** [comment]
I still get the nested pages



I’m running Dash 1.0.1 and the upgraded version of any of the stuff that pip automatically upgrades when you install Dash with it. The upgrade is what kicked this off. Are you running the same installation?

David

**Comment by paul-shannon** [comment]
Here's what I did:
   - used a virtual environment
   -  installed latest of everything metioned in slexil/requirements.txt
   - changed your button click handler to return static/Inferno.html
   - temporarily hardcoded the new route to return exactly static/Inferno.html

This works for me.  I strongly recommend virtual environments:
````
virtualenv --python=/Users/paul/anaconda/bin/python3 ./py363
source py363/bin/activate
cat ../requirements.txt 
pip install -r ../requirements.txt 
pip list | grep dash
dash                            1.0.1    
dash-core-components            1.0.0    
dash-dangerously-set-inner-html 0.0.2    
dash-html-components            1.0.0    
dash-renderer                   1.0.0    
dash-table                      4.0.1    
````

**Comment by davidjamesbeck** [comment]
That did the trick. I’ll see if I can translate this into webapp.py.

So a virtual environment would let you have, say, two different installations of python or dash on the same machine, and switch between them?

David

**Comment by paul-shannon** [comment]
Yes, you are correct about virtual environments.   But more than the switch, to me the main benefit is that my muddled installations (apple 2.7, anaconda 3.6, etc) are no longer waiting to trip me up.

May I persuade you to hang with your demo program until you (until we) completely understand routes, how to invoke them, how they break, how they work?  That is: resist the temptation to patch up webapp.py before acquiring a deep understanding, maybe take notes and add them to the repo? 

 - Paul

**Comment by davidjamesbeck** [comment]
Okay, though any assignment with “deep understanding” attached to it falls into your wheelhouse :-). I’ll standby until you’re comfortable that you know how to proceed.

David

**Comment by paul-shannon** [comment]
My hope is that -you- will do the study!

**Comment by davidjamesbeck** [comment]
I'm always happy to learn new things, so I’m game—but I’m not sure what you would like me to find out. I can play with different paths and file locations ?

David

**Comment by paul-shannon** [comment]
Your idea was better.  You have your hands full with deployment.  How about add notes to the Dash_Tests directory, include everything you can think of, including questions for which we don’t yet have answers.  That directory, and those small working scripts will be part of our extended memory, ready to be visited again when the need arises.

 - Paul

**Comment by davidjamesbeck** [comment]
Okay, sounds like a plan. Probably the most pressing thing is going to be finding out what the “/static/“ part of the path is all about. The change to Dash that got us started down this road is the removal of the static_path kwdarg. Just commenting that out didn’t seem to affect anything in webapp.py as far as I can tell, but we do refer to the “/PROJECTS/“ directory in the @app.server.route('/PROJECTS/<path:urlpath>’) decorator.

One thing I wonder about is whether “/static/“ is a temporary scratch space, in which case we could use it instead of ‘/PROJECTS/‘, thereby not having to have a chron(?) that cleans that directory out every once in a while. (That may be ridiculously off-base.)

David

**Comment by paul-shannon** [comment]
“static” is an arbitrary directory name.   By convention, it’s where one puts non-dynamic html.  It could be anything

It may have a generic meaning also, referring to the class of webserver paths where a project puts static files.

 - Paul

**Comment by davidjamesbeck** [comment]
So, webapp2.py now incorporates the fix in testIFrame2.py, which prevents premature downloading. However, we still have the problem of an infinitely recursive picture of the website showing up in the Show Page textArea before the createWebPage callback is run.
