### ISSUE TITLE
figuring out ualberta deployment

### ISSUE THREAD

**Issue by paul-shannon** [paul-shannon/slexil#43]
@davidjamesbeck 
Just checked in ````slexil/explorations/webDeploy/gunicornTinyDemo/```` to help us bootstrap our way into understanding deployment of slexil for the public at ualberta.  It is a very simple start.

 I also wrote you and Michael directly, hoping to enlist him in this incremental approach.

**Comment by davidjamesbeck** [comment]
Good idea. I also found this on YouTube

https://www.youtube.com/watch?v=tpn-5qPnrrc

I haven’t finished watching it, but it might give us a hint.

David

**Comment by paul-shannon** [comment]
@davidjamesbeck: Some success to report.  I cloned the current slexil onto ````dbeck01````, created a virtual enviroment, pip'd all the required packages, ran all the tests.  See below.

Perhaps you could do the same?

Then the next step might be to 
   - start gunicorn
   - configure apache to redirect to gunicorn

````
connect vpn: vpn.ualberta.net
login
mkdir ~/github
cd ~/github
git clone https://paul-shannon@github.com/paul-shannon/slexil.git
   
sudo apt install python-pip      # gKx&4Lvj
pip install --user virtualenv 
cd ~/github/slexil/tests
~/.local/bin/virtualenv --python=/usr/bin/python3 ./py368
source py368/bin/activate
(py368) pshannon@dbeck01:~/github/slexil/tests$ pip install -r ../requirements.txt
make   # all tests pass
````

**Comment by davidjamesbeck** [comment]
Okay. It has to wait until I’m back in Edmonton on the 16th, though. I apparently don’t have any of my artsrn passwords with me :-(

Great news, though. I’m looking forward to having this up and running

David

**Comment by paul-shannon** [comment]
I’ll try to complete the gunicorn/redirect/etc steps in the next few days.  If our luck holds, you will return to an actually deployed website.
 
 - Paul
