### ISSUE TITLE
Pandas is about to change on us

### ISSUE THREAD

**Issue by davidjamesbeck** [paul-shannon/slexil#45]
Terminal output running webapp2.py produces the following:

/Users/David/Open Source/slexil/audioExtractor.py:58: FutureWarning:

.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#ix-indexer-is-deprecated

Should be easy to fix, for those who know Pandas.

David

**Comment by paul-shannon** [comment]
@davidjamesbeck Updated.  Good catch!

**Comment by paul-shannon** [comment]
@davidjamesbeck I just backed out this change.  Here's why
   table.ix  supports simultaneous use of integer AND  label indexing:
````
  tbl.ix[0, 'TIME_SLOT_REF1']
````
pandas 0.25 deprecates this style, warning us that that flexibility will be phased out, that only .iloc(just integers) or .loc(just labels) will be offered.
I need to refactor the data.frame code in ijalLine to accomodate that.   Let's live with the deprecation warnings for now.  pandas took data.frames from R, my usual and preferred language.  my R programmer's negative assessment of the pandas approach - a dreadful rococo hack -  has just grown a little stronger :}

**Comment by davidjamesbeck** [comment]
Okay, no problem, we can live with it until it no longer works.

David

**Comment by paul-shannon** [comment]
@davidjamesbeck I just updated pandas dataframe 
````
tbl.ix[integer, string] 
````
indexing to use iloc, and only integer positions.  I'll spare you my dismay at this devolution of pandas - the loss of flexibility.  This must seem sensible to those in charge of pandas.

I was unable to run all the tests: 
````
FileNotFoundError: [Errno 2] No such file or directory: '../testTextPyData/GoldenEagle/HHgoldenEagle4.eaf'
````
Maybe that file exists in your filesystem, but not yet on github?

**Comment by paul-shannon** [comment]
@davidjamesbeck I realize I did not spare you my dismay - I spared you the _**details**_ of my dismay.  

Drop me a line when (assuming I analyzed the 'no such file' problem correctly) you check in the missing eaf file?

**Comment by davidjamesbeck** [comment]
Hi, Paul

Sorry about that, I added the testTextPyData folder to .gitignore when I was away because some of the audio files are very big and I was working on a slow wireless connection. I undid that, but it seems that I hadn’t done a commit to the master branch since (which is strange, because I’m pretty sure I had). I also had to merge your changes to ijalLine.py with my fixes for errors involving missing annotations (something else I thought I’d pushed to the repo). I ran the merged file against all our tests and it’s okay. The push to GitHub is in progress as I write.

David

**Comment by davidjamesbeck** [comment]
As I feared, some of these files are too big—what say we comment out the GoldenEagle tests? They are just to test the ability to handle big files and the 24-bit problem, which is particular to scipy, which we’ve moved away from?

David


iMac-2:slexil David$ git push origin master
Enumerating objects: 244, done.
Counting objects: 100% (183/183), done.
Delta compression using up to 4 threads
Compressing objects: 100% (115/115), done.
Writing objects: 100% (116/116), 548.26 MiB | 302.00 KiB/s, done.
Total 116 (delta 44), reused 0 (delta 0)
remote: Resolving deltas: 100% (44/44), completed with 18 local objects.
remote: warning: File testTextPyData/GoldenEagle/GE_full_length.wav is 79.32 MB; this is larger than GitHub's recommended maximum file size of 50.00 MB
remote: warning: File testTextPyData/GoldenEagle/GE_full_length_16.wav is 79.32 MB; this is larger than GitHub's recommended maximum file size of 50.00 MB
remote: warning: File testTextPyData/GoldenEagle/WS_GoldenEagle4.wav is 90.00 MB; this is larger than GitHub's recommended maximum file size of 50.00 MB
remote: error: GH001: Large files detected. You may want to try Git Large File Storage - https://git-lfs.github.com.
remote: error: Trace: cdc9734133cbcf783713ffca255a2e35
remote: error: See http://git.io/iEPt8g for more information.
remote: error: File testTextPyData/GoldenEagle/GE_full_length_32_float.wav is 158.64 MB; this exceeds GitHub's file size limit of 100.00 MB
remote: error: File testTextPyData/GoldenEagle/GE_full_length_32_signed.wav is 158.64 MB; this exceeds GitHub's file size limit of 100.00 MB
remote: error: File testTextPyData/GoldenEagle/GE_full_length_64_float.wav is 317.28 MB; this exceeds GitHub's file size limit of 100.00 MB
remote: error: File testTextPyData/GoldenEagle/WS_GoldenEagle3.wav is 118.98 MB; this exceeds GitHub's file size limit of 100.00 MB
remote: error: File testTextPyData/GoldenEagle/ws_goldeneagle1.wav is 121.67 MB; this exceeds GitHub's file size limit of 100.00 MB
remote: error: File testTextPyData/GoldenEagle/ws_goldeneagle2.wav is 119.23 MB; this exceeds GitHub's file size limit of 100.00 MB
To https://github.com/paul-shannon/slexil.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'https://github.com/paul-shannon/slexil.git'
iMac-2:slexil David$

**Comment by paul-shannon** [comment]
Sounds good to me, David!

 - Paul

**Comment by davidjamesbeck** [comment]
I think it’s done. Trying pulling and running make now.

It took an awfully long time when the major change was NOT uploading a lot of stuff.

David

**Comment by paul-shannon** [comment]
cd tests
make

still looks for  '../testTextPyData/GoldenEagle/HHgoldenEagle4.eaf'  out of test_GoldenEagle4

**Comment by davidjamesbeck** [comment]
That’s really weird. I have only one call to that test in test_AudioExtractor.py and it is commented out on my local copy. I’ll try another push.

David

**Comment by paul-shannon** [comment]
on the master branch?

**Comment by davidjamesbeck** [comment]
Yes, I checked it out explicitly (even though I was pretty sure I was there already). The new push is taking a long time, though, so it thinks that there were differences between GitHub and the local repo. :-(

David

**Comment by paul-shannon** [comment]
I sometimes do
````
git add . --dry-run
````
to see what git wants to do on an add/commit/push

**Comment by davidjamesbeck** [comment]
That got me a blank line. I stopped the slow push and reset my terminal. Here’s the last round of output

iMac-2:slexil David$ git checkout master
Already on 'master'
Your branch is ahead of 'origin/master' by 11 commits.
  (use "git push" to publish your local commits)
iMac-2:slexil David$ git status
On branch master
Your branch is ahead of 'origin/master' by 11 commits.
  (use "git push" to publish your local commits)

nothing to commit, working tree clean
iMac-2:slexil David$ git add . --dry-run
iMac-2:slexil David$ 


So, I’m not sure what those 11 commits on master are—I only edited 4. Can I uncommit them and get a list of files git thinks are different (git status, right?)

David

**Comment by paul-shannon** [comment]
````git log```` might help.   It will list every commit you have ever made, more recent ones first

**Comment by davidjamesbeck** [comment]
It does, but doesn’t tell me what files were committed. I only added those four—.gitignore, ijalLine.py, test_AudioExtractor.py, and test_text_Halkomelem.py—to the commit. I thought that the long list of 127 items it was compressing were all the data files for the tests that were excluded two versions of .gitignore ago—but now that I think of it, I didn’t add them so I don’t know why it would be doing anything with them at all. 

Anyway, I tried a soft reset to undo the last commit

iMac-2:slexil David$ git reset --soft HEAD^
iMac-2:slexil David$ git status
On branch master
Your branch is ahead of 'origin/master' by 10 commits.
  (use "git push" to publish your local commits)

Changes to be committed:
  (use "git reset HEAD <file>..." to unstage)

	new file:   .gitignore.orig

iMac-2:slexil David$ git status
On branch master
Your branch is ahead of 'origin/master' by 10 commits.
  (use "git push" to publish your local commits)

Changes to be committed:
  (use "git reset HEAD <file>..." to unstage)

	new file:   .gitignore.orig

Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	deleted:    .gitignore.orig

We don’t want .gitignore.orig, so I removed it, then tried a general add to see what git picks up on

iMac-2:slexil David$ git add *
The following paths are ignored by one of your .gitignore files:
PROJECTS
__pycache__
bin
morphemeGloss.pyc
venv
Use -f if you really want to add them.

So there’s nothing we need uncommitted it thinks doesn’t match the repo. But then:

iMac-2:slexil David$ git push origin master
Enumerating objects: 320, done.
Counting objects: 100% (197/197), done.
Delta compression using up to 4 threads
Compressing objects: 100% (127/127), done.
Writing objects:  25% (32/128), 4.38 MiB | 328.00 KiB/s   

There’s those 127 files again (?). 

David

**Comment by davidjamesbeck** [comment]
And I see that my copy of ijalLine.py is not the same as the copy on the repo.

**Comment by davidjamesbeck** [comment]
Here are the results of the last attempt at pushing

iMac-2:slexil David$ git push origin master
Enumerating objects: 320, done.
Counting objects: 100% (197/197), done.
Delta compression using up to 4 threads
Compressing objects: 100% (127/127), done.
Writing objects: 100% (128/128), 548.27 MiB | 290.00 KiB/s, done.
Total 128 (delta 51), reused 0 (delta 0)
remote: Resolving deltas: 100% (51/51), completed with 17 local objects.
remote: warning: File testTextPyData/GoldenEagle/GE_full_length.wav is 79.32 MB; this is larger than GitHub's recommended maximum file size of 50.00 MB
remote: warning: File testTextPyData/GoldenEagle/GE_full_length_16.wav is 79.32 MB; this is larger than GitHub's recommended maximum file size of 50.00 MB
remote: warning: File testTextPyData/GoldenEagle/WS_GoldenEagle4.wav is 90.00 MB; this is larger than GitHub's recommended maximum file size of 50.00 MB
remote: error: GH001: Large files detected. You may want to try Git Large File Storage - https://git-lfs.github.com.
remote: error: Trace: c65165d73490c286052d1f73a50bd49d
remote: error: See http://git.io/iEPt8g for more information.
remote: error: File testTextPyData/GoldenEagle/GE_full_length_32_float.wav is 158.64 MB; this exceeds GitHub's file size limit of 100.00 MB
remote: error: File testTextPyData/GoldenEagle/GE_full_length_32_signed.wav is 158.64 MB; this exceeds GitHub's file size limit of 100.00 MB
remote: error: File testTextPyData/GoldenEagle/GE_full_length_64_float.wav is 317.28 MB; this exceeds GitHub's file size limit of 100.00 MB
remote: error: File testTextPyData/GoldenEagle/WS_GoldenEagle3.wav is 118.98 MB; this exceeds GitHub's file size limit of 100.00 MB
remote: error: File testTextPyData/GoldenEagle/ws_goldeneagle1.wav is 121.67 MB; this exceeds GitHub's file size limit of 100.00 MB
remote: error: File testTextPyData/GoldenEagle/ws_goldeneagle2.wav is 119.23 MB; this exceeds GitHub's file size limit of 100.00 MB
To https://github.com/paul-shannon/slexil.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'https://github.com/paul-shannon/slexil.git'
iMac-2:slexil David$

 So it looks like the big files we don’t want are still cued up somehow,

David

**Comment by paul-shannon** [comment]
Hi David,

Ain’t github lovely?! 

Did you put the full path to those files in .gitignore?

Here’s my notes on how to get out of this bind:

* github tips:  clear the "add" list, useful especially if there are really big files queued up (7 dec 2018)

  git reset --soft HEAD^
  git reset --soft HEAD^
  git reset --soft HEAD^

Do it three times, apparently.

**Comment by davidjamesbeck** [comment]
That didn’t work, exactly, but rather than waste more time on this, I took the nuclear option and .zipped my slexil folder, deleted the original and recloned the repo, then altered the files according to what I’d saved in my .zip. I might have to recreate some work I was doing on the GUI in another branch, but I have copies of all that in the directory I’d .zipped.

I think we’re up to date?

David

**Comment by paul-shannon** [comment]
hold off on any more commits, okay?  We have a merge conflict in ijalLine.py I’m trying to figure out.

**Comment by paul-shannon** [comment]
Perhaps you need to check in this file?  It didn’t come down with the latest pull:

 testTextPyData/Raven/newraven_all_errors.eaf

**Comment by davidjamesbeck** [comment]
Yes, I had that too. What happened, I think, is that we are both working on ijalLine.py at the same time. You were down-grading to the new Pandas, and I was trying to handle some errors in the Raven test material. I suspect, now, that my commit of my changes failed because of the big GoldenEagle files and I didn’t notice that it hadn’t taken. Anyway, the ijalLine.py I committed just now is a manual merge of your and my fixes, and I’ve run it against all our tests.

I just sent over the missing test data

David

**Comment by paul-shannon** [comment]
test pass - hurray!

I just pushed ijalLine.py with the merge conflicts resolved (and with all tests passing).

 - Paul

**Comment by davidjamesbeck** [comment]
Whew! Sorry for all this, I think the problems can be put down to my dysfunctional relationship with git. 

Anyway, I’ll finish up my prettification of the GUI and we can merge that branch when it’s done. Then I will start telling people about SLEXIL and we’ll see how many takers there are for early adoption.

David

**Comment by paul-shannon** [comment]
Your zip file/reclone solution to the big-files-stuck-in-limbo problems establishes that you are  a journeyman of git, for sure - and one truly does not want to be any more advanced than that.  (Being a master of git requires a life mis-spent.)  Well done.

**Comment by davidjamesbeck** [comment]
Another opportunity to misspend my life on something. Tempting, but I think I’ll pass
