### ISSUE TITLE
moving on from dash?

### ISSUE THREAD

**Issue by paul-shannon** [paul-shannon/slexil#46]
@davidjamesbeck 
On a friend's advice, I found  a tutorial [How to Build a Single Page App with Python Flask](https://www.youtube.com/watch?v=AsoJL9GPi1k) and used it to create this simple  [demo](https://github.com/ryan-hoffman/calorimetry-project/tree/master/explorations/flask-jquery-singlePageApp).  

You may like this approach.  I certainly do.  I feel like a made a devil's bargain with dash.  After more experiments I may suggest that we migrate SLEXIL away from dash, and towards this style of programming.  

We can support the newly-deployed dash app until I/we have an adequate replacement ready - should we get that far.

**Comment by davidjamesbeck** [comment]
Hi, Paul

Needless to say, I will follow your lead on this. I’m not sure why you don’t like Dash, but from my partial viewing of the tutorial, it does look like Flask allows us to write Python code and run it on our web server. I guess Dash provides us with ready made components that map onto HTML elements and Flask is a bit lower-level? Anyway, if we can do what we need to do and we don’t have to write it in machine language, I’m good.

We’ve run a couple of ELAN projects through the app on artsrn successfully, so we’re in business while we work on updates

David

**Comment by paul-shannon** [comment]
Hi David,

> I’m not sure why you don’t like Dash

The Dash authors try to represent Javascript and DOM operations in Python.  A noble goal, but a very difficult one.   So much of what is easy in Javascript is impossible or awkward when offered in Dash: localStorage, free and easy jQuery element manipulation.

I went through a similar evolution on R Shiny, which inspired Dash.  It took years before Shiny was rich enough to suffice, and in the meantime my slogan was “let R be R, let Javascript be Javascript”.  Seven years later, Shiny is now a delight.

When I chose Dash I assumed - incorrectly - that the python community would deliver rich translation, js <-> python.  This is painfully not so.    I think our current UI for slexil is pretty clunky - that it can be much more natural, much easier to understand, much more responsive.

I will create a small demonstration of this, focusing on just one operation, see how it goes, ask you what you think.

 - Paul

**Comment by davidjamesbeck** [comment]
So, if I understand you right, the GUI part of the app would end up being written in Javascript instead of Dash, which mimics Python syntax and uses Python methods and libraries?

David

**Comment by paul-shannon** [comment]
Hi David,

Dash - which appears as pure python to the programmer - creates HTML and Javascript from some of the python code.  So you get HTML components, and glue code to connect the dash-generated html & javascript, to the python code.  Dash uses websockets, I think, to communicate between your browser and your python session.

This works out s great when the dash designer/author has anticipated our needs.
But when he has not do so, we are out of luck.  Our current webapp2.py has lots of workarounds to try to get it to do what we want.

Dash is currently quite incomplete.  That’s to be expected: it’s new, and it is a big job to translate the capabilities of HTML and Javascript into a python representation.  Some stuff translates awkwardly.

This may be not too different from trying to (imaginatively, expressively, accurately) translate Lushootseed into English.

I do not know that my new approach will improve things.   Therefore I will proceed by creating a small demo of just one aspect of webapp.py, show it to you, see what you think.

You shall decide!

 - Paul

**Comment by paul-shannon** [comment]
@davidjamesbeck I didn't get around to this, and you seem to have gotten all that's needed out of flask.  Well done.
