### ISSUE TITLE
sound files

### ISSUE THREAD

**Issue by davidjamesbeck** [paul-shannon/slexil#47]
Hi, Paul

We should start thinking about what we are using to vet sound files. When we run make, for instance, we get this warning:

python3 test_text_Halkomelem.py
/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/scipy/io/wavfile.py:273: WavFileWarning: Chunk (non-data) not understood, skipping it.
  WavFileWarning)

This is a response to a file that the Hul'q'mi'mun folks were using for one of their texts. Other problems we had in Duncan were:

1) the app rejects files with 16 and 24 bit rates, but ELAN wants these and can't handle 32 bit rate files under at least some conditions
2) the app seems to choke on very large sound files (I have one in the Golden Eagle folder in the testTextPyData folder)

I'll set up a test module for various problems of this type, but maybe you could tell me something about /scipy/io/ and sound file evaluation in general? Are there other packages you are familiar with that we could be using? It seems to me that maximum flexibility is best and we should limit our checks to making sure that X is a soundfile and that we can carve it up as needed.

David

**Comment by paul-shannon** [comment]
Hi David,

In order to keep both code and capabilities well-separated:

  1) adopt a single supported sound format (say, 16-bit wav).
  2) process any proposed sound file into that format, with error checking and reporting
  3) processing would be by a stand-alone slexil class which would grow in capability over time,
     adding support for (and conversions for) more formats - like mp3

With this approach, we don’t complicate webapp.py.   

I picked /scipy/io from a quick web search.  There may be better sound libraries.

 - Paul

**Comment by davidjamesbeck** [comment]
Hi, Paul

I’m not sure how well it would go over with our users if we messed around with the sampling rates of their recordings—though, that said, it looks to me like AudioExtractor logs the sampling rate and outputs at the same rate when it makes the line-by-line files anyway.

I’m having good luck with the built in soundfile module (formerly PySoundfile). We might have to install it manually on the Linux VM, but other than that it has the IO functions we need and doesn’t choke on 24-bit recordings. I need to do some more testing over the next week or so, but this might solve our problem. Or the ones that have come up so far.

Cheers,

David

**Comment by paul-shannon** [comment]
PySoundFile - bravo!

Should be no trouble to install on the VM.

Can you just swap it into AudioExtractor, and all the tests pass?

 - Paul

**Comment by davidjamesbeck** [comment]
I expect so, but I want to try it against a set of sound files of various types that aren’t part of our test suite first. We had several issues with files of different types in Duncan and I’d like to make sure that we don’t have to try something even more sophisticated like librosa, which seems to be popular but looks like overkill to me.

David
