### ISSUE TITLE
Flask problems running slexil on artsrn

### ISSUE THREAD

**Issue by davidjamesbeck** [paul-shannon/slexil#49]
Following up on the problems we are having with Flask on artsrn now that we have an About tab. What I have found is that when you initially load the page, you can go back and forth between the SLEXIL and About tabs and everything is fine, but once you click on the "Download Demo" button (or, presumably the "Download text" button, which is what happened to me on Thursday), everyting breaks. Here is the transcript of a session (user actions in ** **):

+++++++++++++++++++++++
(py368) dbeck@dbeck01:~/github/slexil$ make
gunicorn -w 4 webapp2:server
[2019-09-07 15:16:12 +0000] [10338] [INFO] Starting gunicorn 19.9.0
[2019-09-07 15:16:12 +0000] [10338] [INFO] Listening at: http://127.0.0.1:8000 (10338)
[2019-09-07 15:16:12 +0000] [10338] [INFO] Using worker: sync
[2019-09-07 15:16:12 +0000] [10341] [INFO] Booting worker with pid: 10341
[2019-09-07 15:16:12 +0000] [10342] [INFO] Booting worker with pid: 10342
[2019-09-07 15:16:12 +0000] [10343] [INFO] Booting worker with pid: 10343
[2019-09-07 15:16:12 +0000] [10347] [INFO] Booting worker with pid: 10347

**open browser, go to slexil.artsrn.ualberta.ca**

======= filling in tab
=== callback triggered by grammaticalTermsUploadTextArea change: 
=== callback triggered by associateEAFAndSoundTextArea change: 
=== displayText 'cwpita'
createTierMappingMenusCallback, eaf_filename_hiddenStorage trigger
============= projectDirectory_hiddenStorage changed, updateDownloadTextButtonHref: 
.zip

**click on About tab**

======== filling in tab
====== setting source for about iFrame
serve static

**looks good**
**go back to SLEXIL tab**

======= filling in tab
=== callback triggered by grammaticalTermsUploadTextArea change: 
=== callback triggered by associateEAFAndSoundTextArea change: 
=== displayText 'cwpita'
============= projectDirectory_hiddenStorage changed, updateDownloadTextButtonHref: 
.zip
createTierMappingMenusCallback, eaf_filename_hiddenStorage trigger

**looks good**
** go back to About tab (just to be sure)**

======= filling in tab
====== setting source for about iFrame

**still looks good**
**back to SLEXIL**

======= filling in tab
=== callback triggered by grammaticalTermsUploadTextArea change: 
=== displayText 'cwpita'
=== callback triggered by associateEAFAndSoundTextArea change: 
createTierMappingMenusCallback, eaf_filename_hiddenStorage trigger
============= projectDirectory_hiddenStorage changed, updateDownloadTextButtonHref: 
.zip

**click on Download Demo**

======= filling in tab
=== callback triggered by grammaticalTermsUploadTextArea change: 
=== callback triggered by associateEAFAndSoundTextArea change: 
=== displayText 'cwpita'
createTierMappingMenusCallback, eaf_filename_hiddenStorage trigger
============= projectDirectory_hiddenStorage changed, updateDownloadTextButtonHref: 
.zip

**page reloads, nothing downloads**
**go to About tab**

======= filling in tab
====== setting source for about iFrame
======= filling in tab
=== callback triggered by grammaticalTermsUploadTextArea change: 
=== callback triggered by associateEAFAndSoundTextArea change: 
=== displayText 'cwpita'
createTierMappingMenusCallback, eaf_filename_hiddenStorage trigger
============= projectDirectory_hiddenStorage changed, updateDownloadTextButtonHref: 
.zip
============= projectDirectory_hiddenStorage changed, updateDownloadTextButtonHref: 
.zip
 **About tab (iFrame) now contains the SLEXIL app page**

++++++++++++++++++

The app works fine when run locally on my computer, so it might be something with the way it is being run by gunicorn. Any suggestions about where to start looking/thinking about a solution?

David

**Comment by paul-shannon** [comment]
Hi David,

I just tried to reproduce this, running gunicorn on my laptop.  It seems to run fine.

What do you see if you run gunicorn on your laptop?

 - Paul

**Comment by paul-shannon** [comment]
Here’s another idea, David.

The “about” text is all static, and could be coded directly in dash.html elements - no need for a flask route.

This might cut out significant complexity, and sidestep the problems you see.

 - Paul

**Comment by davidjamesbeck** [comment]
That’s a brilliant idea. gunicorn on my desktop runs just fine, so we’re looking at something with our VM. At least I know how to deal with dash.html elements. I’ll give it a whirl.

David

**Comment by davidjamesbeck** [comment]
the About tab is now coded by dash.html elements and survives clicking "Download demo"; however "Download Demo" still doesn't work—just reloads the page, doesn't download anything.

**Comment by paul-shannon** [comment]
Looking at this now.  Could not find a route for demos/<filename>, so lifting one from webapp.py.  also commenting out the about route. 

Not working yet, but I’ll keep after it.

**Comment by davidjamesbeck** [comment]
Beat me to it! I was just looking at that and noticed it was missing. Great minds think alike, some are just slower at it ...

**Comment by paul-shannon** [comment]
Looks like we stepped on each other’s changes.

I’ll bow out - it’s all yours.   Let me know if I can help.

 - Paul

**Comment by davidjamesbeck** [comment]
Darn, I was going to say the same thing!

All fixed, just copied over the code from webapp.py. Not sure why it got messed with in the first place, I must have tried deactivating it when I was working on the About page iFrame and forgot to restore it? Anyway, the page is up and running and I’ve put it through its paces.

David
