### ISSUE TITLE
webpage, once created, needs to be self-contained: no remote files or images

### ISSUE THREAD

**Issue by paul-shannon** [paul-shannon/slexil#5]
This is now accomplished:
 - ````ijal.css```` and ````ijalUtils.js```` are now included in the html
 - the speaker icon, formerly obtained via http, is now included via a base64 encoded string

@davidjamesbeck This means that any changes you make to ijal.css will be used thereafter.  Please be sure to commit your changes so I see them too.

**Comment by davidjamesbeck** [comment]
2019/2/18: The .css fixes still haven't taken. I don't see a call to ijal.css in text.html.

**Comment by paul-shannon** [comment]
css, javascript and the speaker icon are all now *in* the html.   Do you see it there?  If not, then maybe a "git pull" on the repo?

 - Paul

**Comment by davidjamesbeck** [comment]
I saw the embedded styles, didn't notice that it was the whole style sheet. The "text-align: left;" style for the morpheme tier and/or gloss-tier needs to be set, I guess, if you can't set the text-alignment for the whole grid at once. I wonder if having the external stylesheet isn't better—someone might want to build a site of several texts and need to set the style for the whole site. Maybe loading a .css file into the directory next to text.html would work?

**Comment by paul-shannon** [comment]
So just as the audio files are included in the download zip file, so too for ijal.css?

**Comment by davidjamesbeck** [comment]
Yes, I think that would be good. It gives the end user more flexibility and control over the final presentation
