### ISSUE TITLE
restoring div nesting in ijalLine::toHTML

### ISSUE THREAD

**Issue by paul-shannon** [paul-shannon/slexil#50]
@davidjamesbeck I made this small change just now.  all tests pass.  

I had noticed that our recent html put all subsequent tiers *inside* the speech tier.
Restoring the indentations of the subsequent tiers, in the ````ijalLine.py```` to match the speech tier was a quick fix.
Here is ample output from my current work (this is not relevant to the fix, but is read to hand) as I try to make sense of Daylight line 10, which has confused me for years.  The transcription and the audio seem to be hugely at odds with each other.  Still stumped by "coyo" (k'uy uʔxʷ)?
````
 <div class="speech-tier">tut’ədalgʷiɬ gʷәl tux̌ʷ xʷiʔ uʔxʷ, tuʔaʔ tux̌ʷ xʷiʔ uʔxʷ ƛ’əlayʔ ə coyo gwəsəsaxʷəbabac</div>
          </div>
          <div class="morpheme-tier" style="grid-template-columns: 24ch 6ch 6ch 5ch 5ch 14ch 6ch 5ch 5ch 8ch 2ch 5ch 26ch ;">
            <div class="morpheme-cell">tu=t’əd•al•gʷiɬ</div>
            <div class="morpheme-cell">gʷәl</div>
            <div class="morpheme-cell">tux̌ʷ</div>
            <div class="morpheme-cell">xʷiʔ</div>
            <div class="morpheme-cell">uʔxʷ</div>
````
You may be appalled by the license I have taken, as I contradict two translations arrived at by uniquely skilled linguists (you, Thom ,and Vi). FWIW, this is part of my work in progress, a prosody-centered version of the story -  which I hope, some day, you can critique.  Some of my changes may be credible, some are sure to be misplaced (that is, just simply wrong).

**Comment by davidjamesbeck** [comment]
Hi, Paul

What I have for that part of the text is split into two lines now

tut’ədalgʷiɬ əlgʷəʔ
tu=t’əd•al•gʷiɬ	əlgʷəʔ
past=lined.up•cnn•canoe	pl
‘They lined up the canoes.’
tuʔaʔ dᶻəɬ kʷi ƛ’əlayʔ tux̌ʷ xʷiʔ uʔxʷ gʷəsəsaxʷəbabacs ʔal kʷi sxʷəʔaʔxʷəʔils
tu=ʔaʔ	dᶻəɬ	kʷi	ƛ’əlayʔ	tux̌ʷ	xʷiʔ	uʔxʷ
past=be.there	ptcl	rem	shovel.nose.canoe	just	neg	ptcl
gʷə=s=lə=saxʷəb•abac=s	ʔal	kʷi	s=xʷəʔaʔxʷəʔ–il=s
sbj=nm=prog=jump•body=3po	at	rem	nm=swift–inch=3po
‘There must have been some shovel-nosed canoes but they could not yet jump over them to become swift.’

If what you have is the Hilbert and Hess version, it must have been retranscribed at some point, possibly by me unless there is something somewhere in Thom’s papers where he reworked it and I’ve forgotten. Aside from the stories in the Readers (and even those have the odd error in them), most of Thom and Vi’s texts are relatively unprocessed, in the sense that they didn’t do the checking and rechecking that you need to do to polish up this kind of material, especially when the recordings are so poor. I did a lot of relistening and correction for the Beck and Hess volumes. Not that I got everything, but you could use those as a reference to check against if you’re working with one of those texts.

Cheers,

David

**Comment by paul-shannon** [comment]
> tut’ədalgʷiɬ əlgʷəʔ

Oh, David, I am discouraged!  

Am I delusional to think that the audio from which this transcription is made, the one you published and which I quoted just above, when represented in dumb phonology, sounds like this?

   tu ted al gweel del doke wheech

That’s what I hear.

 - Paul

**Comment by davidjamesbeck** [comment]
Don’t be discouraged, this is tough and you’re much braver than most people when confronted with it. What I found especially hard was that in rapid speech they cram words together and sometimes there is just a consonant or two left where there should have been full syllables. And unstressed particles/clitics like əlgʷəʔ , uʔxʷ , etc. get resyllabified and mangled. Sometimes those become less clear the more you listen.

> On Sep 8, 2019, at 9:11 AM, Paul Shannon <notifications@github.com> wrote:
> 
> 
> > tut’ədalgʷiɬ əlgʷəʔ
> 
> Oh, David, I am discouraged! 
> 
> Am I delusional to think that the audio from which this transcription is made, the one you published and which I quoted just above, when represented in dumb phonology, sounds like this?

Not bad, actually
> 
[tu ted al gweel] [del doke] wheech
[tut’ədalgʷiɬ]       [əlgʷəʔ]    [???]

at the end I actually something ( kʷiƛ’ ? maybe kʷi ? k’ʷit’ ?) which didn’t get transcribed, so may have been discarded as a misspeaking. 

This is good stuff, keep at it. Salishan phonologies are not an easy thing to take on, not by a long shot.

David
