### ISSUE TITLE
HTML tags in tiers cause XML validation failure

### ISSUE THREAD

**Issue by davidjamesbeck** [paul-shannon/slexil#51]
The XML schema for .eaf files does not allow for HTML tags in at least some of the tier types people use (these seem to be defined as simple types and so don't allow child elements). See test/test_XML_schema.py. This affects the way we would apply sub/superscripts in glosses.

Options I can see:

1) Stop validating the .eaf files altogether and deal with malformation errors as they come up in other places (malformation errors are unlikely anyway, since people don't usually build .eaf files by hand and the error would most likely have to originate in ELAN, which is pretty robust by now);
2) Vaildate in some other way that just checks for general well-formedness (unclosed tags, etc.). This would catch the kinds of errors that users might introduce by adding HTML formatting to their glosses;
3) Use our own version of the XSD that allows for child elements (not a good option for a lot of reasons);
4) Trap the particular error "XML parsing error: a simpleType element can't has child elements." and let it pass, let other errors stop execution.

My favorite here is #2, I think, though I'm not sure if there is a way to do it. Feed xmlSchema some sort of more generic description of a valid file?

**Comment by davidjamesbeck** [comment]
After trying this a bit, it looks like attempting to parse the .eaf file before validation checks for well-formedness, so maybe adding this step to webapp2.py would do the trick, though we still have the problem of what to do about failures against the EAF schema.

**Comment by paul-shannon** [comment]
Hi David,

Wishing to get this in context, can you tell me if this captures it?

  Transcribers sometimes use html tags in one or more tiers,  <sub> and <sup> for example, in a glossing tier.
  This is not permitted by the current schema, EAFv3.0.xsd.
  Transcribers typically introduce these html tags using ELAN.
  ELAN permits this, without complaint,
  Indicating that it does not validate against its own schema?

Has there been any discussion of this that you know of within the ELAN community?  If not, do you have access to a forum in which to raise it?

The benefits of validation against a standard schema are many.  Giving them up seems dangerous to me.  If there is no interest in evolving the schema (EAVv3.1.xsd?) I’d favor your option 4.

 - Paul

**Comment by davidjamesbeck** [comment]
Hi, Paul

Yes, your assessment of the problem is correct. I have had submissions to IJAL that used HTML tags and I’m pretty sure that they were added in ELAN, so I think you’re right in thinking that ELAN doesn’t validate files. I’ll look into it. I don’t know how widespread the practice of adding HTML to ELAN projects is. I have a contact name for the ELAN dev team, maybe I can ask them directly.

David

**Comment by davidjamesbeck** [comment]
I just checked and ELAN doesn’t seem to use the .eaf schema for validating its files. I added HTML tags to an .eaf file, saved, closed, and reopened with no ill effects. I’ll write to the developers.

David

**Comment by davidjamesbeck** [comment]
So, solved. ELAN escapes tags when it reads/writes files so users' tags will pass validation. If we add tags manually in a text editor, we need to use escaped characters.
