### ISSUE TITLE
15 (not expected 16) plumedSerpent audio files

### ISSUE THREAD

**Issue by paul-shannon** [paul-shannon/slexil#52]
@davidjamesbeck just did a fresh pull on the master branch - you have been busy!
There's a small discrepancy in test_AudioExtractor.py:
````
--- test_extract_plumedSerpent
Traceback (most recent call last):
  File "test_AudioExtractor.py", line 114, in <module>
    runTests()
  File "test_AudioExtractor.py", line 17, in runTests
    test_extract_plumedSerpent()
  File "test_AudioExtractor.py", line 110, in test_extract_plumedSerpent
    assert(len(fileList) == 16)
````
For what it's worth, I see 15 .wav files in that directory.

**Comment by davidjamesbeck** [comment]
There are 16 in the directory in my repo because I ran webapp2 on that data and it copies the full recording into the audio folder. I think I added the /audio/ directories to .gitignore while I was working on some very large sound files and had slower bandwidth this summer in Duncan. Those files are not in use anymore, so we can either remove the /audio/ folders from .gitignore or manually add the file. I guess if the GitHub repo is going to be accessed, we might think about removing the audio files—they aren’t all public, I’ve just been using them because they are handy on my computer.

David

**Comment by paul-shannon** [comment]
Thanks, @davidjamesbeck.  Any way for me to help?  I pretty often do this myself - that is, see my tests pass on my local machine, and then a colleague reports they fail after a pull.    

After I get all of your updates I want to propose two very small additions to the standard html output file:

  1) A usually empty div, “annotation” added to the end of each line, after the translation element.
     My ad hoc annotation-popup javascript can write into that div.  Being normally empty and hidden,
     I don’t think it will get in the way.
 
  2) An html comment in the header - also invisible. This provides a bit of text for me to replace
     with a few script and style tags which I need to create an annotated version of a page.

It could look like this:

  <head>
    <script src="jquery-3.3.1.min.js"></script>
    <link rel = "stylesheet" type = "text/css" href = "ijal.css" />
    <!—- programmatically-findable header comment —>
  </head>
  <body>

And then could be programmatically transformed, out of a makefile, to

  <head>
    <script src="jquery-3.3.1.min.js"></script>
    <link rel = "stylesheet" type = "text/css" href = "ijal.css" />
    <link rel="stylesheet" type="text/css" href="../pshannon.css" />
    <script src="../showdown.js"></script>
    <script src="../pshannon.js"></script>
    <script src="../kb.js"></script>
   </head>
 <body>

What do you think?

 - Paul

**Comment by davidjamesbeck** [comment]
Hi, Paul

Why don’t I try the easy way for the moment and make sure that git is updating the /audio/ folders. At some point we’ll have to fix the tests not to use other people’s data, or at least not other people’s recordings. I can probably just use one recording of length >= the longest current .wav file we use for all the tests. They will pass even if the sounds we hear don’t match the transcriptions (we’re beyond worrying about that level of undetected error, I think). Unless, we can protect some parts of the GitHub repository? Then we can let people see the code but not the tests and testData?

I like both of those tweaks. Adding a findable annotation element to each line has lots of practical uses for others as well. The add-on to the header is harmless enough, and someone might find it useful someday.

Cheers,

David
