### ISSUE TITLE
URL not found on server

### ISSUE THREAD

**Issue by davidjamesbeck** [paul-shannon/slexil#6]
Running slexil on new machine (Mac Book Pro), the "display web page" button triggers an error "URL not found on this server". But the text.html file is there and works fine, and I didn't have this problem before, on the other machine (iMac). I don't see why the computer would matter though, the directory structure is the same on both (slexil > PROJECTS > Inferno, with slexil as the current working directory).

**Comment by paul-shannon** [comment]
Sorry for the trouble, David.  Please open the javascript console, then paste all you can grab from the error message into this issue.  The URL will be re-presented there.  What happnens if you paste that into another brower?   Please add all the detail you can, including browser version and OS.

 - Paul

**Comment by davidjamesbeck** [comment]
I just tried to recreate the error and it is working now. Just one of those many things, I guess
